/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData clearSky =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fewClouds =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scatteredClouds =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brokenClouds =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData showerRain =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thunderstorm =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mist =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData 02d = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData 09d = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData 10d = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData 04d = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData 11d = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData 13d = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData 50d = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
